import Head from 'next/head';
import React from 'react';
import Footer from '../Footer';
import Header from '../Header';

interface ILayout {
  title: string;
  children: JSX.Element | JSX.Element[];
}

const Layout = ({ title, children }: ILayout) => {
  return (
    <>
      <Head>
        <title>Pawa - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="backGround">
        <Header />
        {children}
        <Footer />
      </div>
    </>
  );
};

export default Layout;
