import type { NextPage } from 'next';
import Head from 'next/head';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import Icon from '../components/Icon';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pawa - Easiest way to pay bills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="container">
        <div className="header mt-10 mb-10">
          <div className="flex justify-content-between">
            <Icon icon="logoLight" />
            <div>navbar here</div>
          </div>
        </div>
      </header>
      <Hero />
      <Footer />
    </>
  );
};

export default Home;
